#!/bin/bash

export FFMPEG_VERSION=7.1.3
export FFMPEG_DIR=${USER_LIB_PATH}/ffmpeg/${FFMPEG_VERSION}
export PATH=${FFMPEG_DIR}/bin${PATH:+:$PATH}
export LD_LIBRARY_PATH=${FFMPEG_DIR}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export PKG_CONFIG_PATH=${FFMPEG_DIR}/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
export MANPATH=${FFMPEG_DIR}/share/man${MANPATH:+:$MANPATH}
